spring.application.name=atlascrm
spring.datasource.url=jdbc:postgresql://${DB_HOST_DEV}:${DB_PORT_DEV}/${DB_NAME}
spring.profiles.active=dev
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

